---
# file: neo4j/vars/mail.yml
neo4j_download: https://neo4j.com/artifact.php?name=neo4j-community-3.1.1-unix.tar.gz
neo4j_archive_path: /tmp/neo4j-community-3.1.1-unix.tar.gz
neo4j_home: /opt/neo4j-community-3.1.1
neo4j_manager_path: /opt/systemd/neo4j-manager.sh
neo4j_hostname: localhost
neo4j_http_port: 7474
neo4j_https_port: 7473
neo4j_bolt_port: 7687
neo4j_dbname: crimegraph.db
neo4j_username: neo4j
neo4j_password: password
neo4j_start_wait: 60 # seconds
neo4j_start_pool: 3 # seconds
neo4j_jvm_heap_min: 8192m
neo4j_jvm_heap_max: 8192m
neo4j_page_cache_size: 10g
