---
# file: flink/vars/mail.yml
flink_download: http://apache.mirrors.spacedump.net/flink/flink-1.2.0/flink-1.2.0-bin-hadoop2-scala_2.11.tgz
flink_archive_path: /tmp/flink-1.2.0-bin-hadoop2-scala_2.11.tgz
flink_home: /opt/flink-1.2.0
flink_manager_path: /opt/systemd/flink-manager.sh
flink_hostname: localhost
flink_port: 8081
flink_start_wait: 60 # seconds
flink_start_pool: 3 # seconds
flink_jobmanager_heap_mb: 2048 # MB
flink_taskmanager_heap_mb: 4096 # MB
flink_taskmanager_slots: 16
flink_taskmanager_memory_preallocate: true
